user nobody;

error_log /Users/oduvanchik/Desktop/test/2026-MAI-Backend-M-Gubareva/Task2/logs/error.log info;
pid /Users/oduvanchik/Desktop/test/2026-MAI-Backend-M-Gubareva/Task2/nginx.pid;

worker_processes 1;

events {
    worker_connections 64;
}

http {
    access_log /Users/oduvanchik/Desktop/test/2026-MAI-Backend-M-Gubareva/Task2/logs/access.log;

    # Upstream для gunicorn
    upstream gunicorn_servers {
        server 127.0.0.1:8000;
    }

    server {
        listen 8080;
        server_name localhost;

        # Location для статических файлов
        location /public/ {
            alias /Users/oduvanchik/Desktop/test/2026-MAI-Backend-M-Gubareva/Task2/public/;
            autoindex on;
        }

        # Location для проксирования на gunicorn
        location /gunicorn/ {
            proxy_pass http://gunicorn_servers/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Корневой location для проверки
        location / {
            return 200 "nginx is working!\n";
            add_header Content-Type text/plain;
        }
    }
}